### ISSUE TITLE
Promote workshops now fully supported

### ISSUE THREAD

**Issue by thomas-bouvier** [trouver-une-fresque/trouver-une-fresque-front#29]
Following https://github.com/trouver-une-fresque/trouver-une-fresque/pull/10, the following workshops should have their logo promoted on the welcome page:

- `Fresque de la Biodiversité`
- `Fresque du Sexisme`
- `Fresque du Numérique`
- `Fresque des Nouveaux Récits`

**Comment by csauge** [comment]
> Following [trouver-une-fresque/trouver-une-fresque#10](https://github.com/trouver-une-fresque/trouver-une-fresque/pull/10), the following workshops should have their logo promoted on the welcome page:
> 
> * `Fresque de la Biodiversité`
> * `Fresque du Sexisme`
> * `Fresque du Numérique`
> * `Fresque des Nouveaux Récits`

Add a fifth one thanks to https://github.com/trouver-une-fresque/trouver-une-fresque/issues/11:
- `Puzzle Climat` (Logo: https://puzzleclimat.org/img/logo-puzzle-climat.png)

**Comment by TimotF** [comment]
> Following [trouver-une-fresque/trouver-une-fresque#10](https://github.com/trouver-une-fresque/trouver-une-fresque/pull/10), the following workshops should have their logo promoted on the welcome page:
> 
> * `Fresque des Nouveaux Récits`

This one was already promoted

**Comment by TimotF** [comment]
> Add a fifth one thanks to [trouver-une-fresque/trouver-une-fresque#11](https://github.com/trouver-une-fresque/trouver-une-fresque/issues/11):
> 
> * `Puzzle Climat` (Logo: https://puzzleclimat.org/img/logo-puzzle-climat.png)

See #30

**Comment by csauge** [comment]
Perfect thank you very much :)
