### ISSUE TITLE
Add workshop `Puzzle Climat`

### ISSUE THREAD

**Issue by thomas-bouvier** [trouver-une-fresque/trouver-une-fresque-front#30]
Workshop website: https://www.puzzleclimat.org/
Workshop `id`: 16

Tagging @csauge

**Comment by csauge** [comment]
i do not see any puzzle climat events https://www.billetweb.fr/multi_event.php?multi=25576&color=4185c1 in the results of https://trouverunefresque.org/

**Comment by thomas-bouvier** [comment]
The frontend is ready to display the events, which still need to get scrapped on my side!
